var navs = [{
	"title": "基本元素",
	"icon": "fa-cubes",
	"spread": true,
	"children": [{
		"title": "按钮",
		"icon": "&#xe641;",
		"href": "button.html"
	}, {
		"title": "临床症状调查表",
		"icon": "&#xe63c;",
		"href": "form.html"
	}, {
		"title": "相关中医症状条目",
		"icon": "&#xe63c;",
		"href": "form2.html"
	}, {
		"title": "生活质量量表",
		"icon": "&#xe63c;",
		"href": "form3.html"
	}, {
		"title": "自评问卷",
		"icon": "&#xe63c;",
		"href": "form4.html"
	}, {
		"title": "健康调查简表",
		"icon": "&#xe63c;",
		"href": "form5.html"
	}, {
		"title": "GERD病人症状表",
		"icon": "&#xe63c;",
		"href": "form6.html"
	}, {
		"title": "胃食管反流症状",
		"icon": "&#xe63c;",
		"href": "form7.html"
	}, {
		"title": "预留form8",
		"icon": "&#xe63c;",
		"href": "form8.html"
	}, {
		"title": "Gerd-Q量表评分",
		"icon": "&#xe63c;",
		"href": "form9.html"
	}, {
		"title": "表格",
		"icon": "&#xe63c;",
		"href": "table.html"
	}, {
		"title": "导航",
		"icon": "&#xe609;",
		"href": "nav.html"
	}, {
		"title": "辅助性元素",
		"icon": "&#xe60c;",
		"href": "auxiliar.html"
	}]
}, {
	"title": "便秘",
	"icon": "fa-cogs",
	"spread": false,
	"children": [{
		"title": "便秘查询",
		"icon": "fa-navicon",
		"href": "navbar.html"
	}, {
		"title": "一般情况调查表",
		"icon": "&#xe62a;",
		"href": "tab.html"
	}, {
		"title": "便秘相关中医条目",
		"icon": "&#xe628;",
		"href": "paging.html"
	}]
}, {
	"title": "第三方组件",
	"icon": "&#x1002;",
	"spread": false,
	"children": [{
		"title": "iCheck组件",
		"icon": "fa-check-square-o",
		"href": "icheck.html"
	}]
}, {
	"title": "地址本",
	"icon": "fa-address-book",
	"href": "",
	"spread": false,
	"children": [{
		"title": "Github",
		"icon": "fa-github",
		"href": "https://www.github.com/"
	}, {
		"title": "QQ",
		"icon": "fa-qq",
		"href": "http://www.qq.com/"
	}, {
		"title": "Fly社区",
		"icon": "&#xe609;",
		"href": "http://fly.layui.com/"
	}, {
		"title": "新浪微博",
		"icon": "fa-weibo",
		"href": "http://weibo.com/"
	}]
}, {
	"title": "这是一级导航",
	"icon": "fa-stop-circle",
	"href": "https://www.baidu.com",
	"spread": false
}, {
	"title": "其他",
	"icon": "fa-stop-circle",
	"href": "#",
	"spread": false,
	"children": [{
		"title": "子窗体中打开选项卡",
		"icon": "fa-github",
		"href": "cop.html"
	}]
}];